# Generated by Django 5.2.8 on 2026-01-25 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScientificOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("is_base_organization", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("acronym", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "keywords",
                    models.CharField(
                        help_text="Enter at least 3 keywords, separated by commas",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField()),
                ("funder", models.CharField(max_length=255)),
                ("project_number", models.CharField(max_length=50)),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("pending", "Pending"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="ongoing",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CHEM", "Chemical Sciences"),
                            ("PHYS", "Physical Sciences"),
                            ("ENG", "Engineering and Technology"),
                            ("AGR", "Agricultural and Veterinary Sciences"),
                            ("MED", "Medical and Health Sciences"),
                            ("MATH", "Mathematics and Computer Science"),
                            ("BIO", "Biological Sciences"),
                            ("EARTH", "Earth and Environmental Sciences"),
                            ("SOC", "Social Sciences"),
                            ("HUM", "Humanities and Arts"),
                        ],
                        max_length=10,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects",
                        to="projects.scientificorganization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("journal", models.CharField(blank=True, max_length=255)),
                (
                    "journal_quartile",
                    models.CharField(
                        choices=[
                            ("Q1", "Q1"),
                            ("Q2", "Q2"),
                            ("Q3", "Q3"),
                            ("Q4", "Q4"),
                            ("NA", "--"),
                        ],
                        default="NA",
                        max_length=2,
                    ),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="Digital Object Identifier",
                        max_length=100,
                    ),
                ),
                (
                    "article_url",
                    models.URLField(blank=True, help_text="Link to the article"),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="articles", to="accounts.scientistprofile"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScientificEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "event_url",
                    models.URLField(blank=True, help_text="Scientific forum website"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[("leader", "Leader"), ("member", "Member")],
                        max_length=20,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="projects.project",
                    ),
                ),
                (
                    "scientist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_memberships",
                        to="accounts.scientistprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("role", "leader")),
                        fields=("project",),
                        name="one_leader_per_project",
                    )
                ],
            },
        ),
    ]
