# Generated by Django 5.2.8 on 2026-01-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scientificorganization",
            name="is_base_organization",
            field=models.BooleanField(default=False, verbose_name="Base organization"),
        ),
    ]
