# Generated by Django 5.2.8 on 2026-01-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("CHEM", "Chemical Sciences"),
                    ("PHYS", "Physical Sciences"),
                    ("ENG", "Engineering and Technology"),
                    ("AGR", "Agricultural and Veterinary Sciences"),
                    ("MED", "Medical and Health Sciences"),
                    ("MATH", "Mathematics and Computer Science"),
                    ("BIO", "Biological Sciences"),
                    ("EARTH", "Earth and Environmental Sciences"),
                    ("SOC", "Social Sciences"),
                    ("HUM", "Humanities and Arts"),
                ],
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="ProjectCategory",
        ),
    ]
