# Generated by Django 5.2.8 on 2026-01-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_scientificorganization_is_base_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="authors",
        ),
        migrations.AddField(
            model_name="article",
            name="authors",
            field=models.TextField(
                blank=True,
                help_text="List of authors as they appear in the publication",
            ),
        ),
    ]
