# Generated by Django 5.2.8 on 2026-01-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_remove_article_authors_article_authors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="publication_date",
        ),
        migrations.AddField(
            model_name="article",
            name="publication_year",
            field=models.PositiveIntegerField(
                blank=True, help_text="Year of publication", null=True
            ),
        ),
    ]
