# Generated by Django 5.2.8 on 2026-01-28 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_remove_article_publication_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "authors",
                    models.TextField(
                        blank=True,
                        help_text="Authors as listed in the presentation/poster",
                    ),
                ),
                (
                    "participation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("poster", "Poster"),
                            ("oral", "Oral presentation"),
                            ("workshop", "Workshop"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="projects.scientificevent",
                    ),
                ),
            ],
        ),
    ]
