# Generated by Django 5.2.8 on 2026-03-14 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_eventparticipation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="organizations",
        ),
        migrations.RemoveField(
            model_name="scientificorganization",
            name="is_base_organization",
        ),
        migrations.CreateModel(
            name="ProjectOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_base_organization",
                    models.BooleanField(
                        default=False, verbose_name="Base organization"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_links",
                        to="projects.scientificorganization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_organizations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "organization"),
                        name="unique_project_organization",
                    )
                ],
            },
        ),
    ]
