# Generated by Django 5.2.8 on 2026-03-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_remove_project_organizations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="organizations",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                through="projects.ProjectOrganization",
                to="projects.scientificorganization",
            ),
        ),
    ]
