# Generated by Django 5.2.8 on 2026-03-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_project_organizations"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="projectorganization",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_base_organization", True)),
                fields=("project",),
                name="one_base_organization_per_project",
            ),
        ),
    ]
