# Generated by Django 5.2.8 on 2026-01-20 08:37

import accounts.managers
import accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ScientistProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="scientist_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "academic_degree",
                    models.CharField(
                        choices=[
                            ("PHD_STUDENT", "PhD Student"),
                            ("PHD", "PhD"),
                            ("DSC", "DSc"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "academic_position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NONE", "—"),
                            ("POSTDOC", "Postdoctoral Researcher"),
                            ("ASSISTANT_PROF", "Assistant Professor"),
                            ("ASSOCIATE_PROF", "Associate Professor"),
                            ("PROFESSOR", "Professor"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("affiliation", models.CharField(max_length=200)),
                (
                    "orcid_id",
                    models.CharField(
                        blank=True,
                        max_length=19,
                        null=True,
                        unique=True,
                        validators=[accounts.validators.OrcidIdValidator],
                    ),
                ),
                (
                    "scopus_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        validators=[accounts.validators.ScopusIDValidator],
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                (
                    "profile_picture_url",
                    models.URLField(
                        blank=True,
                        help_text="Paste a link to your profile picture (optional)",
                        null=True,
                    ),
                ),
                ("research_interests", models.TextField(blank=True)),
                ("is_approved", models.BooleanField(default=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=200, unique=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
