# Generated by Django 5.2.8 on 2026-03-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scientistprofile",
            options={"permissions": [("can_ban_profile", "Can ban profiles")]},
        ),
        migrations.AddField(
            model_name="scientistprofile",
            name="is_reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
