# Generated by Django 5.2.8 on 2026-03-08 15:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_scientistprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scientistprofile",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
