# Generated by Django 5.2.8 on 2026-03-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_report",
            field=models.BooleanField(default=False),
        ),
    ]
